# Generated by Django 6.0.6 on 2026-07-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_waitlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('email', 'product')},
        ),
    ]
