# Generated by Django 6.0.6 on 2026-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_author_description_authorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.DeleteModel(
            name='AuthorImage',
        ),
    ]
