# Generated by Django 6.0.6 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('description', models.TextField(blank=True, verbose_name='Description / Promotion')),
                ('image', models.ImageField(upload_to='carousel_banners/', verbose_name='Banner Image')),
                ('link', models.CharField(blank=True, help_text='URL path where the user redirects (e.g., /catalog/?category=1)', max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Banner',
                'verbose_name_plural': 'Carousel Banners',
            },
        ),
    ]
