# Generated by Django 6.0.6 on 2026-07-09 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_carouselbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Discount Name')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percent')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='shop.category', verbose_name='Apply to Categories')),
                ('genres', models.ManyToManyField(blank=True, related_name='discounts', to='shop.genre', verbose_name='Apply to Genres')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='shop.product', verbose_name='Apply to Specific Products')),
                ('series', models.ManyToManyField(blank=True, related_name='discounts', to='shop.series', verbose_name='Apply to Series')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-discount_percent'],
            },
        ),
    ]
