# Generated by Django 6.0.6 on 2026-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.PositiveIntegerField(blank=True, help_text='Thickness (spine) in mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Width in mm', null=True),
        ),
    ]
